[package]
name = "Knoughts-n-Crosses"
version = "0.1.0"
authors = ["alpha-tango-kilo <atk@aaathats3as.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
